apiVersion: apps/v1
kind: Deployment
metadata:
  name: face-detector
spec:
  selector:
    matchLabels:
      app: face-detector
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: face-detector
    spec:
      containers:
      - name: face-detector
        volumeMounts:
        - mountPath: /dev/video0
          name: dev-video0
        securityContext:
          privileged: true
        image: smithcourtney/camera:v1
        ports:
        - containerPort: 1883
      volumes:
      - name: dev-video0
        hostPath:
          path: /dev/video0
